name: Check Branch
on:
    pull_request:
        branches: [ "main" ]

jobs:
    check_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check Branch
              if: github.base_ref == 'main' && github.head_ref != 'test'
              run: |
                echo: "ERROR: You can only merge from 'test'
                exit 1
