# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
    push:
        branches: [ "main", "test" ]
    pull_request:
        branches: [ "main", "test" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        environment:
            name: Test
            deployment: false

        runs-on: ubuntu-latest
        steps:
            - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: '8.4'
            - uses: actions/checkout@v4

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Copy Env File from Secrets
              run: |
                  touch .env
                  echo ${{secrets.ENV_FILE}} > .env
                  cat .env

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install Dependencies
              uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
              with:
                composer-options: "-q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist"

            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: vendor/bin/phpunit
